### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by Sk4nDev** [timflapper/cordova-spotify-plugin#12]
Hello Tim :))
i would like to ask about the release date of the Android version ? and is it possible to play full-length track using the current version on IOS devices ?
THANKS !

**Comment by timflapper** [comment]
@skandarfessi, Unfortunately I haven't spent any time on this project and it's doubtful the Android version will be available any time soon.

You should be able to play full tracks if you have a premium Spotify account. Unfortunately the Spotify SDK won't allow playing full tracks using a free account.
